import json
import re
import sys

sys.stdout.reconfigure(encoding='utf-8')

with open('scratch/lines_out.txt', 'r', encoding='utf-8') as f:
    raw_lines = [line.split(': ', 1)[1].strip() for line in f if ': ' in line]

lines = raw_lines[23:]

# Comprehensive English dictionary mapping for all Romanian culinary terms
TRANSLATION_MAP = {
    # Mic dejun / Breakfast
    "mic dejun": "classic breakfast",
    "cartofi prăjiți": "french fries",
    "ouă": "eggs",
    "ou": "egg",
    "slănină": "crispy pork fatback",
    "omletă": "omelette",
    "șuncă": "ham",
    "cașcaval": "yellow cheese",
    "țărănească": "farmer's style",
    "ceapă": "onion",
    "chiflă": "bun",
    "cremă de brânză": "cream cheese",
    "ou poșat": "poached egg",
    "bacon": "bacon",
    "sos olandez": "hollandaise sauce",
    "roșii": "tomatoes",
    "salată mixtă": "mixed salad",
    "mix de semințe": "seed mix",
    "platou": "platter",
    "unt": "butter",
    "gem": "jam",
    "mezel": "cold cuts",
    "telemea": "romanian feta cheese",
    "bruschete": "bruschetta",
    "pătrunjel verde": "fresh parsley",
    "ulei de măsline": "olive oil",
    "prăjit": "fried",
    "cremvurști": "boiled frankfurters",
    "lapte": "whole milk",
    "iaurt": "yogurt", "pahar": "glass",
    "unt porționat": "butter portion",
    "cacao": "cocoa",
    "zahăr": "sugar",
    "pudră de cacao": "cocoa powder",
    "cereale": "breakfast cereal",
    "miere": "honey",
    "mici": "traditional mici rolls",
    "pane": "breaded & fried",
    "mămăligă": "polenta",
    "smântână": "sour cream",
    
    # Fast food & Meat
    "burger": "burger",
    "vită": "beef",
    "pui": "chicken",
    "shaorma": "shaorma",
    "cheeseburger": "cheeseburger",
    "ciorbă": "traditional soup",
    "supă": "soup",
    "burtă": "tripe",
    "rădăuțeană": "garlic chicken (rădăuțeană)",
    "gulaș": "goulash",
    "fasole": "beans",
    "afumătură": "smoked pork",
    "ardei iute": "hot pepper",
    "pâine": "bread",
    "gurmandului": "gourmand's",
    "bucătarului": "chef's",
    "grătar": "grilled",
    "pulpe": "thighs",
    "dezosate": "boneless",
    "piept": "breast",
    "rață": "duck",
    "varză roșie": "red cabbage",
    "escalop": "escalope",
    "ciuperci": "mushrooms",
    "crispy": "crispy tenders",
    "aripioare": "wings",
    "șnițel": "schnitzel",
    "hribi": "porcini mushrooms", "trufe": "truffles",
    "cotlet": "pork chop",
    "uriaș": "giant",
    "țigănească": "gypsy style",
    "ceafă": "pork neck",
    "scăriță": "bbq ribs",
    "ciolan": "pork knuckle",
    "rumenit": "roasted",
    "tochitură": "traditional pork stew",
    
    # Seafood & Pasta & Pizza
    "somon": "salmon",
    "teriyaki": "teriyaki",
    "păstrăv": "trout",
    "doradă": "sea bream",
    "mălai": "cornmeal",
    "tigaie picantă": "spicy pan",
    "fructe de mare": "seafood",
    "creveți": "prawns",
    "spaghete": "spaghetti",
    "paste": "pasta",
    "risotto": "risotto",
    "focaccia": "focaccia",
    "pizza": "pizza",
    "garnituri": "side dishes",
    "salate": "salads",
    "desert": "dessert",
    "clătite": "pancakes",
    "papanași": "papanași donuts",
    "vulcan de ciocolată": "chocolate lava cake",
    "înghețată": "ice cream",
    "băuturi": "drinks",
    "răcoritoare": "soft drinks",
    "apă": "water",
    "minerală": "sparkling water",
    "plată": "still water",
    "cafea": "coffee",
    "ceai": "tea",
    "bere": "beer",
    "vin": "wine"
}

print("Reading and cleaning all 280 menu items...")
